### PR TITLE
[part11] - Copy over and adapt materials to the Helsinki University's repository.

### PR DESCRIPTION
**Pull request by TomiHiltunen**
- Copies over and adapts materials for our fork of the university's own project.
    - Adds the styling for exercise blocks.
    - Corrects level of titles.
- Adds the subpages to the index page's navigation.
- Adds a placeholder index page for the part.

**To test the project, run `npm install`, then `npm run start` and access `http://localhost:8000/en/part11/`**

### CODE REVIEW

**Comment by anna-sunberg** [comment]
@TomiHiltunen ~Doesn't build for me. `Error: Cannot find module './part-11.svg'`~ Never mind, it works if you don't go to the main page.

**Review by anna-sunberg — APPROVED** [review]
Great work!

**Review by mhalmagiu — APPROVED** [review]

**Comment by TomiHiltunen** [comment]
> Never mind, it works if you don't go to the main page.

Forgot to mention that it doesn't have the index navigation configured yet.

**Comment by TomiHiltunen** [comment]
Fixed the issues and will be merging now.

**Pull request merged**
